package com.example.httpparam;

import dalvik.bytecode.Opcodes;

/**
 * Created on 2019/6/27.
 * Author: bigwang
 * Description:
 */
public class Temp {
//    {
//        methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "getBody", "()Lokhttp3/MultipartBody$Builder;", null, null);
//        {
//            annotationVisitor0 = methodVisitor.visitAnnotation("Landroidx/annotation/NonNull;", false);
//            annotationVisitor0.visitEnd();
//        }
//        methodVisitor.visitCode();
//        Label label0 = new Label();
//        methodVisitor.visitLabel(label0);
//        methodVisitor.visitLineNumber(105, label0);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitMethodInsn(INVOKESPECIAL, "com/example/httpparam/BaseTest", "getBody", "()Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitVarInsn(ASTORE, 1);
//        Label label1 = new Label();
//        methodVisitor.visitLabel(label1);
//        methodVisitor.visitLineNumber(106, label1);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aBoolean");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aBoolean", "Z");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(Z)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label2 = new Label();
//        methodVisitor.visitLabel(label2);
//        methodVisitor.visitLineNumber(107, label2);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aByte");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aByte", "B");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(I)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label3 = new Label();
//        methodVisitor.visitLabel(label3);
//        methodVisitor.visitLineNumber(108, label3);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aChar");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aChar", "C");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(C)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label4 = new Label();
//        methodVisitor.visitLabel(label4);
//        methodVisitor.visitLineNumber(109, label4);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aDouble");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aDouble", "D");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(D)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label5 = new Label();
//        methodVisitor.visitLabel(label5);
//        methodVisitor.visitLineNumber(110, label5);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aFloat");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aFloat", "F");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(F)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label6 = new Label();
//        methodVisitor.visitLabel(label6);
//        methodVisitor.visitLineNumber(111, label6);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aInt");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aInt", "I");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(I)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label7 = new Label();
//        methodVisitor.visitLabel(label7);
//        methodVisitor.visitLineNumber(112, label7);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aLong");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aLong", "J");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(J)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label8 = new Label();
//        methodVisitor.visitLabel(label8);
//        methodVisitor.visitLineNumber(113, label8);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("aShort");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "aShort", "S");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/String", "valueOf", "(I)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label9 = new Label();
//        methodVisitor.visitLabel(label9);
//        methodVisitor.visitLineNumber(114, label9);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "mTest", "Lcom/example/httpparam/Test;");
//        Label label10 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label10);
//        Label label11 = new Label();
//        methodVisitor.visitLabel(label11);
//        methodVisitor.visitLineNumber(115, label11);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("mTest");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "mTest", "Lcom/example/httpparam/Test;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Object", "toString", "()Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        methodVisitor.visitLabel(label10);
//        methodVisitor.visitLineNumber(117, label10);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 1, new Object[]{"okhttp3/MultipartBody$Builder"}, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "cc", "[I");
//        Label label12 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label12);
//        Label label13 = new Label();
//        methodVisitor.visitLabel(label13);
//        methodVisitor.visitLineNumber(118, label13);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("cc");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "cc", "[I");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "toString", "([I)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        methodVisitor.visitLabel(label12);
//        methodVisitor.visitLineNumber(120, label12);
//        methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("xxxxx");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "name", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label14 = new Label();
//        methodVisitor.visitLabel(label14);
//        methodVisitor.visitLineNumber(121, label14);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "girls", "[Ljava/lang/String;");
//        Label label15 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label15);
//        Label label16 = new Label();
//        methodVisitor.visitLabel(label16);
//        methodVisitor.visitLineNumber(122, label16);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("girls");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "girls", "[Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "toString", "([Ljava/lang/Object;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        methodVisitor.visitLabel(label15);
//        methodVisitor.visitLineNumber(124, label15);
//        methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file", "Ljava/io/File;");
//        Label label17 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label17);
//        Label label18 = new Label();
//        methodVisitor.visitLabel(label18);
//        methodVisitor.visitLineNumber(125, label18);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("123File");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file", "Ljava/io/File;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/File", "getName", "()Ljava/lang/String;", false);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file", "Ljava/io/File;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/io/File", "getName", "()Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        methodVisitor.visitLabel(label17);
//        methodVisitor.visitLineNumber(127, label17);
//        methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "filein", "Lcom/example/httpparam/FileInput;");
//        Label label19 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label19);
//        Label label20 = new Label();
//        methodVisitor.visitLabel(label20);
//        methodVisitor.visitLineNumber(128, label20);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "filein", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "key", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "filein", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "filein", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "filein", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        methodVisitor.visitLabel(label19);
//        methodVisitor.visitLineNumber(130, label19);
//        methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file2", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "key", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file2", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file2", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "file2", "Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label21 = new Label();
//        methodVisitor.visitLabel(label21);
//        methodVisitor.visitLineNumber(131, label21);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files", "Ljava/util/List;");
//        Label label22 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label22);
//        Label label23 = new Label();
//        methodVisitor.visitLabel(label23);
//        methodVisitor.visitLineNumber(132, label23);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files", "Ljava/util/List;");
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
//        methodVisitor.visitVarInsn(ASTORE, 2);
//        Label label24 = new Label();
//        methodVisitor.visitLabel(label24);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 1, new Object[]{"java/util/Iterator"}, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
//        methodVisitor.visitJumpInsn(IFEQ, label22);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitVarInsn(ASTORE, 3);
//        Label label25 = new Label();
//        methodVisitor.visitLabel(label25);
//        methodVisitor.visitLineNumber(133, label25);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitLdcInsn("testCustomFiles");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label26 = new Label();
//        methodVisitor.visitLabel(label26);
//        methodVisitor.visitLineNumber(134, label26);
//        methodVisitor.visitJumpInsn(GOTO, label24);
//        methodVisitor.visitLabel(label22);
//        methodVisitor.visitLineNumber(136, label22);
//        methodVisitor.visitFrame(Opcodes.F_CHOP, 1, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files2", "Ljava/util/List;");
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
//        methodVisitor.visitVarInsn(ASTORE, 2);
//        Label label27 = new Label();
//        methodVisitor.visitLabel(label27);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 1, new Object[]{"java/util/Iterator"}, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
//        Label label28 = new Label();
//        methodVisitor.visitJumpInsn(IFEQ, label28);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitVarInsn(ASTORE, 3);
//        Label label29 = new Label();
//        methodVisitor.visitLabel(label29);
//        methodVisitor.visitLineNumber(137, label29);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "key", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label30 = new Label();
//        methodVisitor.visitLabel(label30);
//        methodVisitor.visitLineNumber(138, label30);
//        methodVisitor.visitJumpInsn(GOTO, label27);
//        methodVisitor.visitLabel(label28);
//        methodVisitor.visitLineNumber(139, label28);
//        methodVisitor.visitFrame(Opcodes.F_CHOP, 1, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files3", "Ljava/util/List;");
//        Label label31 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label31);
//        Label label32 = new Label();
//        methodVisitor.visitLabel(label32);
//        methodVisitor.visitLineNumber(140, label32);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files3", "Ljava/util/List;");
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
//        methodVisitor.visitVarInsn(ASTORE, 2);
//        Label label33 = new Label();
//        methodVisitor.visitLabel(label33);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 1, new Object[]{"java/util/Iterator"}, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
//        methodVisitor.visitJumpInsn(IFEQ, label31);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitVarInsn(ASTORE, 3);
//        Label label34 = new Label();
//        methodVisitor.visitLabel(label34);
//        methodVisitor.visitLineNumber(141, label34);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "key", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label35 = new Label();
//        methodVisitor.visitLabel(label35);
//        methodVisitor.visitLineNumber(142, label35);
//        methodVisitor.visitJumpInsn(GOTO, label33);
//        methodVisitor.visitLabel(label31);
//        methodVisitor.visitLineNumber(144, label31);
//        methodVisitor.visitFrame(Opcodes.F_CHOP, 1, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files4", "[Lcom/example/httpparam/FileInput;");
//        Label label36 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label36);
//        Label label37 = new Label();
//        methodVisitor.visitLabel(label37);
//        methodVisitor.visitLineNumber(145, label37);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files4", "[Lcom/example/httpparam/FileInput;");
//        methodVisitor.visitVarInsn(ASTORE, 2);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitInsn(ARRAYLENGTH);
//        methodVisitor.visitVarInsn(ISTORE, 3);
//        methodVisitor.visitInsn(ICONST_0);
//        methodVisitor.visitVarInsn(ISTORE, 4);
//        Label label38 = new Label();
//        methodVisitor.visitLabel(label38);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 3, new Object[]{"[Lcom/example/httpparam/FileInput;", Opcodes.INTEGER, Opcodes.INTEGER}, 0, null);
//        methodVisitor.visitVarInsn(ILOAD, 4);
//        methodVisitor.visitVarInsn(ILOAD, 3);
//        methodVisitor.visitJumpInsn(IF_ICMPGE, label36);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitVarInsn(ILOAD, 4);
//        methodVisitor.visitInsn(AALOAD);
//        methodVisitor.visitVarInsn(ASTORE, 5);
//        Label label39 = new Label();
//        methodVisitor.visitLabel(label39);
//        methodVisitor.visitLineNumber(146, label39);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 5);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "key", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 5);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 5);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 5);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label40 = new Label();
//        methodVisitor.visitLabel(label40);
//        methodVisitor.visitLineNumber(145, label40);
//        methodVisitor.visitIincInsn(4, 1);
//        methodVisitor.visitJumpInsn(GOTO, label38);
//        methodVisitor.visitLabel(label36);
//        methodVisitor.visitLineNumber(149, label36);
//        methodVisitor.visitFrame(Opcodes.F_CHOP, 3, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files5", "Ljava/util/Map;");
//        Label label41 = new Label();
//        methodVisitor.visitJumpInsn(IFNULL, label41);
//        Label label42 = new Label();
//        methodVisitor.visitLabel(label42);
//        methodVisitor.visitLineNumber(150, label42);
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/Test", "files5", "Ljava/util/Map;");
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
//        methodVisitor.visitVarInsn(ASTORE, 2);
//        Label label43 = new Label();
//        methodVisitor.visitLabel(label43);
//        methodVisitor.visitFrame(Opcodes.F_APPEND, 1, new Object[]{"java/util/Iterator"}, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
//        methodVisitor.visitJumpInsn(IFEQ, label41);
//        methodVisitor.visitVarInsn(ALOAD, 2);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map$Entry");
//        methodVisitor.visitVarInsn(ASTORE, 3);
//        Label label44 = new Label();
//        methodVisitor.visitLabel(label44);
//        methodVisitor.visitLineNumber(151, label44);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getKey", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "java/lang/String");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "data", "Ljava/io/File;");
//        methodVisitor.visitVarInsn(ALOAD, 0);
//        methodVisitor.visitVarInsn(ALOAD, 3);
//        methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
//        methodVisitor.visitTypeInsn(CHECKCAST, "com/example/httpparam/FileInput");
//        methodVisitor.visitFieldInsn(GETFIELD, "com/example/httpparam/FileInput", "filename", "Ljava/lang/String;");
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/example/httpparam/Test", "guessMimeType", "(Ljava/lang/String;)Ljava/lang/String;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/MediaType", "parse", "(Ljava/lang/String;)Lokhttp3/MediaType;", false);
//        methodVisitor.visitMethodInsn(INVOKESTATIC, "okhttp3/RequestBody", "create", "(Ljava/io/File;Lokhttp3/MediaType;)Lokhttp3/RequestBody;", false);
//        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "okhttp3/MultipartBody$Builder", "addFormDataPart", "(Ljava/lang/String;Ljava/lang/String;Lokhttp3/RequestBody;)Lokhttp3/MultipartBody$Builder;", false);
//        methodVisitor.visitInsn(POP);
//        Label label45 = new Label();
//        methodVisitor.visitLabel(label45);
//        methodVisitor.visitLineNumber(152, label45);
//        methodVisitor.visitJumpInsn(GOTO, label43);
//        methodVisitor.visitLabel(label41);
//        methodVisitor.visitLineNumber(154, label41);
//        methodVisitor.visitFrame(Opcodes.F_CHOP, 1, null, 0, null);
//        methodVisitor.visitVarInsn(ALOAD, 1);
//        methodVisitor.visitInsn(ARETURN);
//        Label label46 = new Label();
//        methodVisitor.visitLabel(label46);
//        methodVisitor.visitLocalVariable("file", "Lcom/example/httpparam/FileInput;", null, label25, label26, 3);
//        methodVisitor.visitLocalVariable("file", "Lcom/example/httpparam/FileInput;", null, label29, label30, 3);
//        methodVisitor.visitLocalVariable("file", "Lcom/example/httpparam/FileInput;", null, label34, label35, 3);
//        methodVisitor.visitLocalVariable("file", "Lcom/example/httpparam/FileInput;", null, label39, label40, 5);
//        methodVisitor.visitLocalVariable("entry", "Ljava/util/Map$Entry;", "Ljava/util/Map$Entry<Ljava/lang/String;Lcom/example/httpparam/FileInput;>;", label44, label45, 3);
//        methodVisitor.visitLocalVariable("this", "Lcom/example/httpparam/Test;", null, label0, label46, 0);
//        methodVisitor.visitLocalVariable("builder", "Lokhttp3/MultipartBody$Builder;", null, label1, label46, 1);
//        methodVisitor.visitMaxs(6, 6);
//        methodVisitor.visitEnd();
//    }
}
